language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install codecov
script:
    - make test
after_success:
    - codecov