import logging
import os

LOGGING_LEVEL = logging.getLevelName(os.getenv("LOGGING_LEVEL", "DEBUG"))
LOGGING_FORMAT = "%(asctime)s.%(msecs)06dZ|%(levelname)s: sdx-gateway: %(message)s"

COLLECT_QUEUE = os.getenv('RABBIT_SURVEY_QUEUE', 'sdx_gateway_collect')
SDX_GATEWAY_EQ_RABBITMQ_USER = os.getenv('SDX_GATEWAY_EQ_RABBITMQ_USER', 'rabbit')
SDX_GATEWAY_EQ_RABBITMQ_PASSWORD = os.getenv('SDX_GATEWAY_EQ_RABBITMQ_PASSWORD', 'rabbit')
QUARANTINE_QUEUE = 'bridge_quarantine'
RABBIT_EXCHANGE = 'exchange'
EQ_QUEUE = os.getenv('RABBIT_GATEWAY_QUEUE', 'survey')
SDX_GATEWAY_EQ_RABBITMQ_HOST = os.getenv('SDX_GATEWAY_EQ_RABBITMQ_HOST', '0.0.0.0')
SDX_GATEWAY_EQ_RABBITMQ_HOST2 = os.getenv('SDX_GATEWAY_EQ_RABBITMQ_HOST2', '0.0.0.0')
SDX_GATEWAY_EQ_RABBIT_PORT = '5672'
HEALTHCHECK_DELAY_MS = '5000'
HEARTBEAT_INTERVAL = "?heartbeat_interval=5"

SDX_GATEWAY_SDX_RABBITMQ_PORT = '5672'
SDX_GATEWAY_SDX_RABBITMQ_HOST = os.getenv('SDX_GATEWAY_SDX_RABBITMQ_HOST', '0.0.0.0')
SDX_GATEWAY_SDX_RABBITMQ_USER = os.getenv('SDX_GATEWAY_SDX_RABBITMQ_USER', 'rabbit')
SDX_GATEWAY_SDX_RABBITMQ_PASSWORD = os.getenv('SDX_GATEWAY_SDX_RABBITMQ_PASSWORD', 'rabbit')
